// Re-exportar timeouts específicos desde constants.js para compatibilidad
export {
  MESSAGE_SEND_TIMEOUT,
  WELCOME_MESSAGE_DELAY,
  BOT_MESSAGE_REGISTER_DELAY,
  SESSION_INIT_DELAY,
  SESSION_DELETE_DELAY,
  SESSION_DELETE_DELAY_LONG,
  RECONNECT_DELAY,
  ONBOARDING_DELAY,
  QR_GENERATION_TIMEOUT,
  TRIAL_SESSION_WAIT_TIMEOUT,
  CONVERSATION_TIMEOUT,
  HUMAN_INACTIVITY_TIMEOUT,
  BOT_MESSAGE_WINDOW,
  MESSAGE_COOLDOWN,
  MAX_MESSAGE_AGE_MS,
  MIN_SESSION_UPTIME_FOR_NO_TIMESTAMP,
  CONFIG_CACHE_TTL,
  COOLDOWN_CACHE_TTL,
  HEARTBEAT_INTERVAL
} from './constants.js';

